{% set version = "2.17.3" %}

package:
  name: requests
  version: {{ version }}

source:
  fn: requests-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/r/requests/requests-{{ version }}.tar.gz
  sha256: 8d29f97ed1541709b57caddb77bb20592411d7ca10ec4f03275f49ee8456e225

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - chardet >=3.0.2,<3.1.0
    - idna >=2.5,<2.6
    - urllib3 >=1.21.1,<1.22
    - certifi >=2017.4.17

test:
  imports:
    - requests

about:
  home: http://python-requests.org
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Python HTTP for Humans.'

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - msarahan
    - pelson
    - sigmavirus24
    - ocefpaf
