{% set version = "2.19.0" %}

package:
  name: requests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests/requests-{{ version }}.tar.gz
  sha256: cc408268d0e21589bcc2b2c248e42932b8c4d112f499c12c92e99e2178a6134c

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - chardet >=3.0.2,<3.1.0
    - idna >=2.5,<2.7
    - urllib3 >=1.21.1,<1.23
    - certifi >=2017.4.17

test:
  imports:
    - requests

about:
  home: http://python-requests.org
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Python HTTP for Humans.'

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - pelson
    - sigmavirus24
    - ocefpaf
