{% set version = "2.26.0" %}

package:
  name: requests
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/requests/requests-{{ version }}.tar.gz
  sha256: b8aa58f8cf793ffd8782d3d8cb19e66ef36f7aba4353eec859e74678b01b07a7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - chardet >=3.0.2,<5
    - idna >=2.5,<3
    - urllib3 >=1.21.1,<1.27
    - certifi >=2017.4.17

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - requests

about:
  home: http://python-requests.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Requests is an elegant and simple HTTP library for Python, built with ♥.
  dev_url: https://github.com/psf/requests

extra:
  recipe-maintainers:
    - jakirkham
    - kalefranz
    - mcg1969
    - mingwandroid
    - msarahan
    - pelson
    - sigmavirus24
    - ocefpaf
    - carlodri
