travis:
  secure:
    BINSTAR_TOKEN: PoyYtO04dSs2/EH0oYJMLz+m1jsHpjcT67T13boPIH7u8hiGvK14KaoIdhX16I/SGjM5vU+z1KN6SRTU+Jl/eXLv7G4GE/cG1MW5WDGDr0kFGXzyto2KbKzQXjnopMB4VGT/K+k1T5TTrwJUvwMBPRwk7S5YkiHm6NuU+tJ4is07NL5Uek9aCVgGRFDJ5rhqlMxqYGVAIDonqzcRvJMs4fkD8nK5YDPfJxFzixNjS+IJSy77CHb8QLL7jzPslblco6VXQ05gQVh6fPNHCf8pYGmOiw85CmAp7PBFwVMKUXrT2v8FgAnhs1x7OgoXk02WhxMyRTimNr6dyQFSyedFJVitXvzbBN+/Yq76JktRvMsAQYm42yPNS97AXxn/o/s0F9klYvSQQpNKeIYuYNRmIALFivQqDXL37YsK9GgU96SAmUmUp/n0RlAJqfdtY69M6+edgVI+Qm4aBkfmeK93muGhuR0DCNabcJdtodV4n9zF8pqbywRsxYDDQcnnTB1dAUmY/v+/H0APyYeKTyqf7+L1t2/ugpzYh+UjMI0D8ptxmL52yg/SzTvVdHCvFO5VxbPLe9rMvzCWgSqZkuYkl43DY2frWFOV0rMYno0cMpo5584BO+XsTELr5PRJa8CuYJ5hNPRrDwCIZlaTGlilPZ1D9X8YhzhcEGNClz9yaDQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
